### ISSUE TITLE
but just to suggest about nodes merger images 

### ISSUE THREAD

**Issue by AkoZ** [WASasquatch/ComfyUI_Preset_Merger#1]
for the merging easy, the name you know , but the curves drawing are far easier to understand, 
also just suggest 👍 **_to put a little image 
or even a sort of icon to chose between the different merging effects ;)_** 
cheers !
and thanK you full for this add-on 
AkOZ

**Comment by WASasquatch** [comment]
I'm sorry, I don't think I understand. ComfyUI doesn't have the tools necessary to launch any sort of editors, place images or text on nodes, etc. It's a very bare-bones, limiting system. You have to create all the edits to the front end via extensions.
