### ISSUE TITLE
name of the Preset

### ISSUE THREAD

**Issue by za-wa-n-go** [WASasquatch/ComfyUI_Preset_Merger#3]
Can I change the notation name of a preset?
When saving an image for merge testing, I want to use the preset notation, but it stops with an error if it contains special symbols such as "*".

**Comment by WASasquatch** [comment]
You can edit nodes.py and change the preset names and the node will use them. You can PR a more appropriate naming if you like too and if it looks good we can merge it.

**Comment by za-wa-n-go** [comment]
For a variety of reasons, it was not possible to pull request.
The following changes were made and we are pleased with the results.
SAWTOOTH also.

"SMOOTHSTEP_2"
"SMOOTHSTEP_OVER_2":
