### ISSUE TITLE
How about adding block parameters?

### ISSUE THREAD

**Issue by toyxyz** [WASasquatch/ComfyUI_Preset_Merger#4]
Thank you for your wonderful work! There is one suggestion. I need to add another custom node to test the block parameters before creating a new preset. How about adding a manual mode to adjust the block parameter in addition to preset mode to Preset Merger? Like the image below.

![image](https://github.com/WASasquatch/ComfyUI_Preset_Merger/assets/8006000/10d75826-7b23-4c19-bf00-9d04cba0942a)

**Comment by WASasquatch** [comment]
Just use ModelMergeBlocksNumber. The point of the Preset node is TOO hide those blocks, cause the presets are controlling the block values.
